### ISSUE TITLE
Configurable endpoints Requirement for metrices

### ISSUE THREAD

**Issue by abhay40711cs** [jochen-schweizer/express-prom-bundle#10]
In case of working with different packages to get the metrices of node application , there is a need to have a configurable endpoint of collection of metrices instead of default one /metrices

localhost/matrices : It should be configurable

**Comment by disjunction** [comment]
This has been addressed here: https://github.com/jochen-schweizer/express-prom-bundle/pull/1

I haven't documented this feature though, as almost ALL applications I've seen so far have one /metrics endpoint, which also is exactly ```/metrics```. I didn't want to encourage most likely wrong decision.

Here's how you can control route yourself:

```js
const app = express();
const promBundleInstance = require('express-prom-bundle')({autoregister: false});

// this registers stats collection
// but will not create a route for /metrics because of autoregister: false
app.use(promBundleInstance); 

// now you can register metrics route manually
// wherever you want
app.use('/my-metrices', promBundleInstance.metricsMiddleware);
```

Hope this helps!

**Comment by abhay40711cs** [comment]
Thanks for your response
