### ISSUE TITLE
Express 5 already works, but is limited by `package.json`?

### ISSUE THREAD

**Issue by jnatten** [jochen-schweizer/express-prom-bundle#131]
Hi there,

We're in the process of upgrading our express version to v5 and afaict `express-prom-bundle` already works perfectly with the exception that it directly depends on express v4 in `package.json`.

I only seem to find `express` usage in the tests and types, could we move `express` to a `devDependency` maybe?

**Comment by disjunction** [comment]
Thanks for raising this. You can now switch to version 8.0.0

Made 3 releases:
- 7.0.1 - dependabot updates from March 2024
- 7.0.2 - latest dependabot updates
- 8.0.0 - switch to express@5
