### ISSUE TITLE
Should prom-client be a peer dependency?

### ISSUE THREAD

**Issue by n-rook** [jochen-schweizer/express-prom-bundle#20]
I recently started using express-prom-bundle, but ran into a problem:

1. My server imported prom-client directly and exported some metrics on /metrics.
2. I added express-prom-bundle, but set autoregister to false, because I had already defined a /metrics route myself.
3. express-prom-bundle happily registered its metrics. Unfortunately for me, it installed its metrics on *its own instance of the prom-client module*. This meant that when I called promClient.register.metrics() in my own route, I didn't get the metrics from express-prom-bundle, because they were installed on the wrong global registry!

I managed to fix this by forking express-prom-bundle and turning prom-client into a peer dependency. I think this is the right way to go: If prom-client is a peer dependency, express-prom-bundle will use the same version of prom-client as the top-level Node server. But it's not backwards compatible.

(The fork is here: https://github.com/askspoke/express-prom-bundle.)

What do you think?

**Comment by disjunction** [comment]
starting from version 5.0.1 prom-client is a peer dependency

thanks again for pointing this out and apologies that it took me soooooo long

**Comment by n-rook** [comment]
No problem, thanks for making the change!
