### ISSUE TITLE
Question: How do I configure a different port for the metrics

### ISSUE THREAD

**Issue by poteirard** [jochen-schweizer/express-prom-bundle#25]
Hello ! First of all thank you for you amazing work on this repo :)

In my company we are using Prometheus for all the java projects and I wanted to achieve the same for our node servers as well. 

All the endpoints of metrics however has to be in a specific port (different from the app server). Something like `my-url.com:9000/metrics`.

Is it possible to achieve that with this repo?

Thank you :)

**Comment by goooseman** [comment]
It is not so obvious, because this middleware attaches to express, which is listening on one of the ports. Middleware can not expose itself to a different port. This can not be solved by extending the API of this library, but can be done on the integration side in your code.

To solve this issue, we need one more express app, which has only `/metrics` endpoint. But we need to register statistics from our main express app. In the end I came up with the following:

``` metrics.js
const express = require("express");
const promBundle = require("express-prom-bundle");

const metricsRequestMiddleware = promBundle({
  includePath: true,
  includeMethod: true,
  autoregister: false, // Do not register /metrics
  promClient: {
    collectDefaultMetrics: {
    },
  },
});
const { promClient, metricsMiddleware } = metricsRequestMiddleware;
// promClient here is the prom-client object 

// Metrics app to expose /metrics endpoint
const metricsApp = express();
metricsApp.use(metricsMiddleware);

module.exports = { metricsRequestMiddleware, metricsApp };
```

``` app.js
const express = require("express");
const app = express();
const { metricsRequestMiddleware } = require("@server/app/metrics");

// We are using metricsRequestMiddleware which register statistics from main express app
app.use(metricsRequestMiddleware);
```

``` server.js
const app = require("./server/app");
const { metricsApp } = require("./server/app/metrics");

const server = http.createServer(app); // Main server
const metricsServer = http.createServer(metricsApp); // Metrics server
server.listen(5000);
metricsServer.listen(9090);
```

**Comment by poteirard** [comment]
It works like a charm. Thanks a lot for the code and the comments !

**Comment by shaharsol** [comment]
@goooseman @poteirard just implemented this solution in my app and found out that indeed I can now access the `/metrics` endpoint on port 9090, however I can *still* access the metrics via the main app port i.e `localhost:3000/metrics`. 
Am I missing something? Is there anyway to limit access to the metrics endpoint on the main app port?

**Comment by shaharsol** [comment]
My other issue with that solution is that I can't seem to use the ordering of the `use`s to determine which route will be measured and which will not. Everything is included regardless of where I `use` the `metricsRequestMiddleware`.

**Comment by lehno** [comment]
Same problem as you @shaharsol

**Comment by elaijuh** [comment]
https://github.com/jochen-schweizer/express-prom-bundle/blob/23cedb9f05d87eb03a66389597cf499930ba275f/src/index.js#L132
@shaharsol

**Comment by nasonfish** [comment]
Here's a solution that seems to work for me.

```typescript

const app = express();
const metricsApp = express();

const metricsMiddleware = promBundle({
    includeMethod: true,
    includePath: true,
    autoregister: false,
});

app.use(metricsMiddleware);

// app.use(.....)
app.listen(config.PORT, () => {
    console.log('Server listening on port', config.PORT);
});

metricsApp.use(metricsMiddleware.metricsMiddleware);

metricsApp.listen(config.METRICS_PORT, () => {
    console.log('Metrics listening on port', config.METRICS_PORT);
});
```

It appears to register the metrics endpoint correctly in the metrics server, while collecting the actual metrics from the app.

**Comment by ath88** [comment]
I added an option that makes this far easier. Check out #101.
