### ISSUE TITLE
extraMasks not working

### ISSUE THREAD

**Issue by oreporan** [jochen-schweizer/express-prom-bundle#39]
Hey, I can't seem to get the extraMasks of the `urlValueParser` working, my setup looks like this - 

```js
promBundle({ 
   includeMethod: true, 
   includePath: true, 
   buckets: webRequestsBuckets,
   urlValueParser: {
        extraMasks: [
            /^some-email-regex$/,
        ],
    }
})
```

The regex is not catching, I know this because I'm using the same `UrlValueParser` library for my logger in a different area of my code - 

Works:
```js
const parser = new UrlValueParser({
    extraMasks: [
       /^some-email-regex$/,
    ],
});
....
parser.replacePathValues(req.originalUrl, '#val')
``` 

any ideas why? I saw from your code that the options are being passed, so I can't figure out the issue...

Also, in your [includePath  example](https://github.com/jochen-schweizer/express-prom-bundle#more-details-on-includepath-option) you omit the `includePath : true`

**Comment by oreporan** [comment]
Was an internal issue, closing

**Comment by oreporan** [comment]
Turns out the problem was that my regex: 
`/^(([^<>()[]\\.,;:s@"]+(.[^<>()[]\\.,;:s@"]+)*)|(".+"))@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}])|(([a-zA-Z-0-9]+.)+[a-zA-Z]{2,}))$/`

When turned to a string by just converting `/` to `'` was not the same.
since `urlValueParser` allows Regex, I think in the typescript definition you should allow `(string|RegExp)[] `

**Comment by disjunction** [comment]
good point. Will fix together with the docs. Thanks!

**Comment by oreporan** [comment]
Also - any chance to get an example of `transformLabels ` ? :)

**Comment by disjunction** [comment]
it here: https://github.com/jochen-schweizer/express-prom-bundle/blob/master/advanced-example.js#L13

**Comment by oreporan** [comment]
ah thanks, didn't see that

Also, it seems that even when I pass

myLongRegex.source
Its still not catching, but if I pass a regex (bypass your typescript definition) it is working.
Perhaps an issue with urlParser?
