### ISSUE TITLE
Need a way to exclude certain routes in the configuration

### ISSUE THREAD

**Issue by himelnagrana** [jochen-schweizer/express-prom-bundle#59]
Right now to avoid certain routes to be excludes from the metrics - we need to do (as per documentation):
`app.use("/((?!foo))*", promBundle({includePath: true}));`

It is a bit redundant in our use case as we are using this bundle inside a wrapper and using that wrapper into couple of node apps and we need to exclude multiple routes to be entered into metrics.

It would have been a great thing if somehow the `excluded` routes can be put inside this bundle configuration object. Or is it something existing and I have missed?

**Comment by yacineb** [comment]
Hi, done in this PR : https://github.com/jochen-schweizer/express-prom-bundle/pull/70

I've added a custom filter criteria on express request, this allows more control and it's more generic

**Comment by yacineb** [comment]
closed ==> done using the new bypass option
