### ISSUE TITLE
Authenticate metrics endpoint

### ISSUE THREAD

**Issue by cxn-pszakacs** [jochen-schweizer/express-prom-bundle#61]
I want some basic authorization on the /metrics endpoint so that not everyone can get the data from my application. 
Is there a way I can add an authentication callback function as option with the request as a parameter?

Thanks for your help.

**Comment by mohsin51** [comment]
+1

**Comment by mohsin51** [comment]
@cxn-pszakacs 
i was able to tackle this using 
`const basicAuth = require('express-basic-auth')
authorizer: (username, password) => {
      const userMatches = promuser && basicAuth.safeCompare(username, promuser)
      const passwordMatches = prompassword && basicAuth.safeCompare(password, prompassword)
      return userMatches & passwordMatches
    }`
here promuser and prompassword are credentials and requests having basic auth with this credentials will have access to metrics path

**Comment by disjunction** [comment]
correct. Auth should not be the concern of this library.
