### ISSUE TITLE
Can custom metrics (counters, gauges) be emitted via express-prom-bundle?

### ISSUE THREAD

**Issue by h2rashee** [jochen-schweizer/express-prom-bundle#65]
This is a more high-level question about the package in general.

Is the sole purpose of this package to handle standard Express metrics only or does it support also pushing through custom metrics as well i.e. avoid having to double-integrate with prom-client?

**Comment by jorge07** [comment]
All metrics defined with prom-client package will be exposed automatically.

**Comment by disjunction** [comment]
The purpose of this package is to **add** the express metrics to already existing metrics one has with prom-client. It is NOT supposed to proxy any additional metrics to the prom-client simply because you can do that directly.
