### ISSUE TITLE
Exclude /metrics route

### ISSUE THREAD

**Issue by piks2252** [jochen-schweizer/express-prom-bundle#68]
Hello, 
First of all thank you so much for this library, I appreciate you hard word,
Now i don't want to display `/metrics` request in my grafana dashboard, Is there any way to exclude `/metrics` route
I tried `app.use("/((?!metrics))*", promBundle({includePath: true}));`, but It blocks the `/metrics` and returns no route found which was the only access point (target) for my Prometheus server to access metrics data.
I just want to exclude "/metrics" path in my collection which is polluting my app's APIs.
Thanks

**Comment by disjunction** [comment]
Hi. The `/metrics` path is excluded automatically, you don't need to do anything. Have you tested it?

**Comment by gmeher** [comment]
HI @disjunction, Thanks for your quick reply. @piks2252 and me works on same team.
please find the attachment, "/metrics" is retained in my data metrics and same is being scraped by Prometheus server, which is polluting our business/app APIs.
![Screen Shot 05-11-2020 at 14 26](https://user-images.githubusercontent.com/28529749/98219625-438dd200-1f73-11eb-8f34-3b1d6fa47c4e.png)
![Screen Shot 05-11-2020 at 14 26 - 2](https://user-images.githubusercontent.com/28529749/98219653-4c7ea380-1f73-11eb-939a-673f117c2b61.png)

**Comment by disjunction** [comment]
I'm afraid it's due to the way you use the module or a potential conflict with multiple prom clients. Could you provide the how the `prom-client` and `express-prom-bundle` are defined in your `project.json` and also how you call `promBundle()` in your app?

**Comment by disjunction** [comment]
... and if you do anything directly with `prom-client`, please mention it too

**Comment by gmeher** [comment]
Hi @disjunction ,Thanks.  we were running swagger-stats as well in our Application server.
after removing, it worked fine.

**Comment by piks2252** [comment]
Thanks @disjunction for your support.
