### ISSUE TITLE
promtool reports errors

### ISSUE THREAD

**Issue by RichardWright** [jochen-schweizer/express-prom-bundle#72]
Noticed the scrape endpoint was working with prometheus so ran the prom tool. I got the following output

'nodejs_active_handles_total non-counter metrics should not have "_total" suffix'

As this is standard stuff how is this working for everyone else?

**Comment by disjunction** [comment]
I was using the recommendation from Prometheus itself. It seems to be the same as before: https://prometheus.io/docs/practices/naming/

In the first version is was named differently and I was told off by the Prometheus community ;), and thus changed the label to what it is now.

Please provide more details on your argument and make a concrete suggestion, if you feel the label is wrong.
