### ISSUE TITLE
Unintentional(?) breaking peer dep change in 6.3.1

### ISSUE THREAD

**Issue by billyjanitsch** [jochen-schweizer/express-prom-bundle#76]
It seems that the intention of https://github.com/jochen-schweizer/express-prom-bundle/commit/a3c15b1645f3aebff4da4e19301201decae67fc8 was to support both `prom-client@12` and `prom-client@13`, but https://github.com/jochen-schweizer/express-prom-bundle/commit/f4677ce6c6b54cc3d379e6259f0176e9f4fbbbc2 updated the peer dependency to `"prom-client": "^13.0.0"`, which makes it a peer dependency error to install the package alongside `prom-client@12`.

This can be fixed by updating the peer dependency to `"prom-client": "^12.0.0 || ^13.0.0"` and publishing a new release.

If you _did_ want to restrict the peer dependency range to `^13.0.0`, then that should be done in a major version (i.e., `express-prom-bundle@7.0.0` instead of `6.3.1`) because it's generally considered a breaking change to modify peer dependencies in a backwards-incompatible way.

**Comment by disjunction** [comment]
Great catch! Indeed it was unintentional. I changed the dep to simple `>=12.0.0` Yeah, I know I take the risk with potential v14, but so far there was only ONE breaking incompatibility from 12 to 13. Worst case I will - make another patch.

The change has now been released as a patch version `6.3.2`
