### ISSUE TITLE
Helped needed...

### ISSUE THREAD

**Issue by RichardWright** [jochen-schweizer/express-prom-bundle#79]
Hi!

I compared the metrics that came out of this and another project and this project makes alot of sense. I've decided to dump our current implementations and move over to this project - however due to a registry already beingin place (this one - https://www.npmjs.com/package/@opentelemetry/exporter-prometheus) I'm trying to get the PrometheusExporter in as a promRegistry. 

Not much joy though.

The error. `Type 'PrometheusExporter' is missing the following properties from type 'Registry': metrics, clear, resetMetrics, registerMetric, and 7 more.ts(2740)
index.d.ts(37, 5): The expected type comes from property 'promRegistry' which is declared here on type 'Opts'`

Have you ever integrated this project with opentelemetries prometheus exporter?

**Comment by disjunction** [comment]
I have no experience with @opentelemetry/exporter-prometheus. Is it a real functional problem or just the typing is wrong somewhere? Did you try to force the type cast and see if it works at all?

**Comment by RichardWright** [comment]
They look totally different.

I think this, combined with the difference between prom client and open telem has made me realise I need to move away from it and use this project instead. Issue solved!
