### ISSUE TITLE
authorization on the /metrics url?

### ISSUE THREAD

**Issue by rushabhnagda11** [jochen-schweizer/express-prom-bundle#8]

**Comment by rushabhnagda11** [comment]
I can give a PR for this

**Comment by disjunction** [comment]
sorry, I consider auth should be out of this lib. You have so many easy options to implement it, that i don't see why the lib should suggest anything specific.

**Comment by rushabhnagda11** [comment]
isn't /metrics exposed to the world in that case? my bad if this sounds very naive and there is a way to internally expose it

**Comment by disjunction** [comment]
I don't see why it must be coupled with this one. It's not a framework, but a library with one task.

You can add auth using other libs designed for that. It will cost you 2 lines of code. 

```javascript
const basicAuth = require('express-basic-auth');
app.use('/metrics', basicAuth({users: { 'admin': 'supersecret' }}));
````

**Comment by mikepuglisi** [comment]
Can you provide a more complete example of authentication of the /metrics endpoint. I'm trying to apply the example as follows but it isn't working:

```
    const basicAuth = require('express-basic-auth');
    const bundle = promBundle({
      blacklist: [/up/],
      buckets: [0.1, 0.4, 0.7],
      includeMethod: true,
      includePath: true,
      customLabels: { year: null },
      transformLabels: labels => Object.assign(labels, {year: new Date().getFullYear()}),
      promClient: {
        collectDefaultMetrics: {
          timeout: 1000
        }
      }
    });
    
    app.use('/metrics', basicAuth({users: { 'admin': 'supersecret' }}));
    app.use(bundle);
```

**Comment by disjunction** [comment]
@mikepuglisi  I've tried exactly your sample and it does work. Could you post the entire source code you're testing with? Probably in your case you have a different order?

**Comment by mikepuglisi** [comment]
The problem was due to my lack of understanding of what "works" means. I was expecting a prompt of asking for the username password.

I now realize you would need the following property to result in a prompt.


```
    app.use('/metrics', basicAuth({
      users: { 'admin': 'supersecret' },
      challenge: true,
    }))
```

Thank you for you assistance.

**Comment by marwenbk** [comment]
how the bundle will be able to fetch the request if the request won't be authorized on /metrics ?
