### ISSUE TITLE
Package consuming 10gb of virtual memory

### ISSUE THREAD

**Issue by Pauss** [jochen-schweizer/express-prom-bundle#88]
Hello, 
I'm using this package : express-prom-bundle": "^6.3.6.
Recently i've noticed it's consuming ~10gb of virtual memory alone. 

Here's my package.json : 
{
  "name": "app",
  "version": "1.0.0",
  "description": "Test Server for Kubernetes Cluster",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon index.js"
  },
  "author": "Paula Tanasa",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1",
    "morgan": "^1.10.0",
    "nodemon": "^2.0.7",
    "express-prom-bundle": "^6.3.6"
  }
}

Here's the 'top' command log: 
![image](https://user-images.githubusercontent.com/18573691/126775430-e4ebcd08-b593-40eb-9d7d-2ce88a109a06.png)

Can you take a look and provide any feedback? 
Thank you.

**Comment by disjunction** [comment]
what makes you think the culprit is express-prom-bundle?

**Comment by Pauss** [comment]
don't know but without this package, virtual memory stays lower than 1mb
![image](https://user-images.githubusercontent.com/18573691/126781166-a800b2b0-75ba-48c3-bab1-71de2a4526a0.png)

**Comment by disjunction** [comment]
The library requires a peer dependency - prom-client. I don't see it in the dependencies of the your project. Have you checked, if it even works? Do you get the expected response from `/metrics` endpoint?

**Comment by Pauss** [comment]
I've let only this 4 packages for testing the virtual memory. 

The library works well (along prom-client), no doubt about it. 
Maybe you can make the same test and see (with and without express-prom-bundle).

My concern was only about virtual memory it takes.

**Comment by Pauss** [comment]
hmm..after more testing, seems that when importing this lib with 'import' ("type": "module") and not with 'require' is causing this pb...
