### ISSUE TITLE
Disable http_request_duration_seconds

### ISSUE THREAD

**Issue by toymachiner62** [jochen-schweizer/express-prom-bundle#94]
Is it possible to completely disable the default `http_request_duration_seconds` metric?

**Comment by disjunction** [comment]
This is the only metric provided by the library. How else do you use it?

**Comment by toymachiner62** [comment]
It provides us the middleware function. We use prom-client to create all our own metrics along with this middleware.

**Comment by disjunction** [comment]
You shouldn't use this library for that. Exposing a metric is as easy as:

```js
const promClient = require('prom-client')

app.get('/metrics', function(req,res) {
  res.status(200).set('Content-Type', 'text/plain')
  promClient.register.metrics()
    .then(output => res.end(output))
})
```

(I wish prom-client had an explicit example in their docs)
